### ISSUE TITLE
undefined method key? for nested arrays

### ISSUE THREAD

**Issue by celsworth** [dry-rb/dry-schema#118]
With this schema, directly copied from https://dry-rb.org/gems/dry-schema/nested-data/:

```ruby
schema = Dry::Schema.Params do
  required(:people).each do
    schema do
      required(:name).filled
      required(:age).filled(:integer, gteq?: 18)
    end
  end
end
```

I can break it by passing an unexpected array instead of a hash for one of the people:

```ruby
[3] pry(main)> schema.call(people: [[]])
NoMethodError: undefined method `key?' for []:Array
from /Users/chris/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/dry-logic-0.5.0/lib/dry/logic/predicates.rb:23:in `key?'
```

Is this a bug, or is there some other way I should be avoiding blowing up when passed this sort of invalid input?

**Comment by solnic** [comment]
Semantics changed and `each` + `schema` are now simpler building blocks that don't add type checks anymore. Change it to `array` + `hash`, respectively and it'll work, so:

``` ruby
require 'dry/schema'

schema = Dry::Schema.Params do
  required(:people).array(:hash) do
    required(:name).filled
    required(:age).filled(:integer, gteq?: 18)
  end
end

puts schema.(people: [{name: '', age: 17}, {name: 'piotr', age: 35}]).inspect
# #<Dry::Schema::Result{:people=>[{:name=>"", :age=>17}, {:name=>"piotr", :age=>35}]} errors={:people=>{0=>{:name=>["must be filled"], :age=>["must be greater than or equal to 18"]}}}>
```

ps. above syntax is available in `0.5.0` that I *just released*.

**Comment by solnic** [comment]
oops, it is actually a bug, sorry for being too quick to close this - re-opening...

**Comment by solnic** [comment]
for the record, it's choking at the key map level (so before it even gets to the rule application) https://github.com/dry-rb/dry-schema/blob/4c5d167eb6b193d120caddce2592bcff3f3a9346/lib/dry/schema/key.rb#L49
