### ISSUE TITLE
filled(:integer) returns "int?" error instead of "filled?"

### ISSUE THREAD

**Issue by ndan** [dry-rb/dry-schema#134]
**Bug**

`filled(:integer)` and `filled(:string)` should return the same error message when input is empty

Actual behaviour:

`filled(:string)` returns "must be filled" (`filled?` error)
`filled(:integer)` returns "must be an integer"  (`int?` error)

**To Reproduce**

```ruby
schema = Dry::Schema.Params do
  required(:email).filled(:string)
  required(:user_id).filled(:integer)
end

errors = schema.call(email: '', user_id: '').errors
errors.to_h # => {:email=>["must be filled"], :user_id=>["must be an integer"]}
```

**Expected behavior**

`filled(:integer)` and `filled(:string)` should behave the same and return `filled?` error

**gem version**

```ruby
Dry::Schema::VERSION # => "1.0.2"
```

**Comment by solnic** [comment]
I'm not sure if this is a bug. Filled is meant to be used to check if a value is filled. Type specs check if a value has the expected type. If you pass an empty string to a params schema, it will be coerced to `nil`, thus `int?` check fails and gives you the error.

**Comment by solnic** [comment]
uhm sorry this has nothing to do with coercing empty strings to nils, this only happens for `maybe`, not `filled`.

so, in this case, what happens is that `filled(:string)` checks if it's a non-empty string, whereas with `filled(:integer)` it checks if it's an integer, so coercion of an empty string fails, and you get back an empty string, which is not an integer, so you get an error.

If I understand it correctly, what you expected is that `filled?` would take precedence and it would do `filled? & int?` - but it's the other way around, as it does `int? & filled?`.

I need to think about this some more.

**Comment by ndan** [comment]
Putting `filled?` behind `int?` means `filled?` will never be called.
So, `filled(:integer)` is equal to `value(:integer)`. The same is true for `filled(:bool)`, `filled(:date)`, etc.

**Comment by ndan** [comment]
I think, the way it works now makes a lot of sense for API, but not for HTML forms. Which leads me to an idea of making different behavior for `Dry::Schema.Params` and `Dry::Schema.JSON`, but I'm not sure if it's a good idea at all.

Here is the use case for HTML form:
1. There is a form with `<input name="name">` and `<select name="user_id">`
2. The user leaves the form empty and press submit
3. The user should see "must be filled" for `name` and `user_id`

**Comment by flash-gordon** [comment]
For the record, this can (and likely should) be achieved with filtering
```ruby
dry-schema> s = params { required(:age).filter(:filled?).value(:integer) }
=> #<Dry::Schema::Params keys=["age"] rules={:age=>"key?(:age) AND key[age](int?)"}>
dry-schema> s.(age: "")
=> #<Dry::Schema::Result{:age=>""} errors={:age=>["must be filled"]}>
dry-schema> s.(age: "foo")
=> #<Dry::Schema::Result{:age=>"foo"} errors={:age=>["must be an integer"]}>
dry-schema> s.(age: "18")
=> #<Dry::Schema::Result{:age=>18} errors={}>
```
This process can be automated in some way.

**Comment by ndan** [comment]
I can also use `value(:filled?)` which is the same as `filter(:filled?)` but provides a nice inspection: `(filled? AND int?)`

```ruby
Dry::Schema.Params do
  required(:ids).value(:filled?).value(:integer)
end
=> #<Dry::Schema::Params keys=["ids"] rules={:ids=>"key?(:ids) AND key[ids](filled? AND int?)"}>
```

**Comment by flash-gordon** [comment]
filtering is different because it prevents coercion empty strings to an integer, thus performance-wise it's better

**Comment by solnic** [comment]
I will experiment with using `filter` under the hood. We can use it for all value types that need to be coerced **after** checking `filled?`, so ie:

```ruby
# this
required(:foo).filled(:string)
# translates to:
required(:foo) { str? & filled? }

# this
required(:foo).filled(:array)
# translates to:
required(:foo) { array? & filled? }

# but this
required(:foo).filled(:integer)
# translates to:
required(:foo).filter(:filled?).value(:int?)
```
