### ISSUE TITLE
Schema with nested optional value fails in v1.0.2

### ISSUE THREAD

**Issue by madejejej** [dry-rb/dry-schema#136]
**Describe the bug**

Hi! I'm trying to upgrade our code to use the newest, yet unreleased dry-validation. I stumbled upon this bug which is best described with code. We have a lot of fine-grained schemas for different rules in our API, so in this case we don't want to show any errors on `body`. We use dry-validation rules to form more complex rules for this schema.

**To Reproduce**

```ruby
require 'dry-schema'

schema = Dry::Schema.Params do
  optional(:body).schema do
    optional(:user_traits).maybe(:hash?)
  end
end


puts schema.({ 'body' => 7 })
```

```
Traceback (most recent call last):
	17: from test.rb:10:in `<main>'
	16: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/processor.rb:92:in `call'
	15: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/result.rb:37:in `new'
	14: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/processor.rb:93:in `block in call'
	13: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/processor.rb:93:in `each'
	12: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/processor.rb:94:in `block (2 levels) in call'
	11: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/rule_applier.rb:32:in `call'
	10: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/rule_applier.rb:32:in `each'
	 9: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-schema-1.0.2/lib/dry/schema/rule_applier.rb:35:in `block in call'
	 8: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/operations/implication.rb:20:in `call'
	 7: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/operations/key.rb:39:in `call'
	 6: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/operations/set.rb:13:in `call'
	 5: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/operations/set.rb:13:in `map'
	 4: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/operations/set.rb:13:in `block in call'
	 3: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/operations/implication.rb:17:in `call'
	 2: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/rule/interface.rb:121:in `call'
	 1: from /Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/rule/interface.rb:121:in `[]'
/Users/kacper/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-logic-1.0.0/lib/dry/logic/predicates.rb:23:in `key?': undefined method `key?' for 7:Integer (NoMethodError)
```

**Expected behavior**

The hash `{ 'body' => 7 }` is valid according to this schema. There should be no errors raised, and the schema itself should have no errors.

**Your environment**

- Affects my production application: **NO**
- Ruby version: 2.6.3
- OS: OSX

**Comment by solnic** [comment]
This is expected, change `schema` to `hash`.

**Comment by madejejej** [comment]
@solnic with `hash` you will get an error on `body`. I don't want that.

**Comment by solnic** [comment]
Not sure if I understand. If you pass `7`, which is not a hash, you will get an error under `body` key which is totally expected. You specify that the value under `body` must be a hash, so you get an error under `body` 😄

**Comment by madejejej** [comment]
I know it might not make sense from that standpoint. But if you have a lot of fine-grained rules, does it make sense that each separate rule validates that the body is a `hash` and adds the same error over and over again?

It might be better to make a softer assumption: if body is present and it's not a hash, that's ok. But if it's a hash, it must conform to the `schema`.

**Comment by solnic** [comment]
This is exactly how it works. Schema rules won't be applied if it's not a hash.

**Comment by madejejej** [comment]
But then you get an error on the body.

```ruby
require 'dry-schema'

schema = Dry::Schema.Params do
  optional(:body).hash do
    optional(:user_traits).maybe(:hash?)
  end
end


p schema.({ 'body' => 7 }).errors.to_h # {:body=>["must be a hash"]}
```

If you have tons of rules to validate, it's impossible to keep them in one schema. So we'd have more fine-grained schemas with different rules. One of our schemas can simply look like this:

```ruby
required(:body).filled(:hash?)
```

and then we have 20 other schemas that validate different fields in the `body` schema, like in my first example. 

Now, you can either deduplicate the error messages so you don't see "body must be a hash" 20 times, or, you could allow your smaller schemas not to fail if `body` is incorrect. Does that make sense?

**Comment by solnic** [comment]
I need to see an example because I'm not sure if I understand.
