### ISSUE TITLE
array[:integer] doesn't expand to array? & each { int? }

### ISSUE THREAD

**Issue by ndan** [dry-rb/dry-schema#140]
The [docs](https://dry-rb.org/gems/dry-schema/basics/type-specs/#using-arrays-with-member-types) say `array[:integer]` expands to `array? & each { int? }`, but it expands to `array?` 

It leads to errors like this:
```ruby
schema = Dry::Schema.Params do
  required(:user_ids).value(array[:integer])
end

schema.(user_ids: ['asdf']).success? # => true
```

It happens because `array[:integer]` is just a shortcut for `Dry::Types['array'].of(Dry::Types['params.integer']).lax`, so the docs or behavior needs to be fixed.

**Comment by solnic** [comment]
This is a bug. The intention is always to infer predicates even from complex types. I'll fix it.
