### ISSUE TITLE
array(:hash) breaks coercion of inherited rules

### ISSUE THREAD

**Issue by ndan** [dry-rb/dry-schema#143]
When a child has `array(:hash)` and doesn't receive an array it breaks coercion of parent's rules

```ruby
parent = Dry::Schema.Params do
  optional(:id).value(:integer)
end

child = Dry::Schema.Params(parent: parent) do
  optional(:user).array(:hash)
end

invalid_input = {
  'id' => '1',
  'user' => nil # must be an array of hashes
}

failed_result = child.(invalid_input)

# Should not return :id=>["must be an integer"]
failed_result.errors.to_h
# => {:id=>["must be an integer"], :user=>["must be an array"]}

# Should convert :id into Integer
failed_result.to_h
=> {:user=>nil, :id=>"1"}
```

**Your environment**
```ruby
Dry::Schema::VERSION
# => "1.0.3"
```

**Comment by flash-gordon** [comment]
I'm not sure if the `parent` option is part of public API, is it documented somewhere?

**Comment by ndan** [comment]
No docs, only tests: [dry-schema](https://github.com/dry-rb/dry-schema/blob/master/spec/integration/params/defining_base_form_spec.rb) and [dry-validation](https://github.com/dry-rb/dry-validation/blob/master/spec/integration/contract/inherited_spec.rb)
[This one](https://github.com/dry-rb/dry-schema/blob/master/spec/unit/dry/schema/params_spec.rb#L49) looks legit

Is there a right way to share top-level rules for dry-schema/dry-validation?

**Comment by flash-gordon** [comment]
Thanks, I actually misinterpreted this option, now it seems what you did should work. 

For the record, I'm not sure about being the "right way" but you can always share rules via a proc + `instance_exec(&SharedRules)`

**Comment by ndan** [comment]
The bug is [here](https://github.com/dry-rb/dry-schema/blob/master/lib/dry/schema/dsl.rb#L214):
```ruby
def type_schema
  if parent
    parent.type_schema.schema(types)
  else
    type_registry['hash'].schema(types).lax
  end
end
```

`type_schema` comparison:
```ruby
plain_schema = Dry::Schema.Params do
  optional(:id).value(:integer)
  optional(:user).array(:hash)
end

parent = Dry::Schema.Params do
  optional(:id).value(:integer)
end

child = Dry::Schema.Params(parent: parent) do
  optional(:user).array(:hash)
end

plain_schema.type_schema
# => #<Dry::Types[Lax<Constructor<Schema<keys={Lax<id?: Constructor<Nominal<Integer meta={required: false, maybe: false}> fn=Dry::Types::Coercions::Params.to_int>> Lax<user?: Constructor<Array<Constructor<Hash fn=Dry::Types::Coercions::Params.to_hash>> fn=Dry::Types::Coercions::Params.to_ary>>}> fn=Dry::Types::Coercions::Params.to_hash>>]>

child.type_schema
# => #<Dry::Types[Lax<Constructor<Schema<keys={Lax<id?: Constructor<Nominal<Integer meta={required: false, maybe: false}> fn=Dry::Types::Coercions::Params.to_int>> user?: Constructor<Array<Constructor<Hash fn=Dry::Types::Coercions::Params.to_hash>> fn=Dry::Types::Coercions::Params.to_ary>}> fn=Dry::Types::Coercions::Params.to_hash>>]>
```

The problem is that `parent.type_schema.schema(types)` doesn't wrap own types with `Lax` (see `Lax<user?:` vs `user?:`)
