### ISSUE TITLE
`filled?` predicate is not applied for params schemas with constructor types

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-schema#152]
**Describe the bug**

It may appear as a quite narrow use case but it's actually not. You usually want to strip spaces _before_ you check a string for emptiness.

**To Reproduce**

```ruby
module Types
  include Dry::Types()

  NotEmptyString = String.constructor do |str, &block|
    if str.nil?
      block.(nil)
    else
      result = str.strip

      if result.empty?
        block.(result)
      else
        result
      end
    end
  end
end
```
```ruby
params { required(:foo).filled(Types::NotEmptyString) }.(foo: '   ')
=> #<Dry::Schema::Result{:foo=>""} errors={}>
```

**Expected behavior**

Same as we have for `schema` currently:

```ruby
dry-schema> schema { required(:foo).filled(Types::NotEmptyString) }.(foo: '   ')
=> #<Dry::Schema::Result{:foo=>""} errors={:foo=>["must be filled"]}>
```

**Your environment**

Irrelevant.

**Comment by flash-gordon** [comment]
for the record,
```ruby
dry-schema> params { required(:foo).value(Types::NotEmptyString, :filled?) }.(foo: '   ')
=> #<Dry::Schema::Result{:foo=>""} errors={:foo=>["must be filled"]}>
```
works just fine

**Comment by solnic** [comment]
To fix this, we need to introduce a new step that will apply types after key map is applied. This is needed in general for filter rules to work in cases like this one (I'm sure there's more).

It's also a good opportunity to make step API feel more like a first-class feature.
