### ISSUE TITLE
Retrieving errors with option full: true adds whitespace even in locales that don't have whitespace between words

### ISSUE THREAD

**Issue by cmcolinh** [dry-rb/dry-schema#161]
Here is some example code that reproduces this issue in 1.0.0
```
class MyContract < Dry::Validation::Contract
  config.messages.backend        = :i18n
  config.messages.default_locale = :ja
  params do
    required(:name).filled(:string)
  end
  rule(:name){key.failure(:oh_no) if values[:name].eql?('oh no')}
end
```
with ja.yml
```
ja:
  dry_validation:
    errors:
      filled?: "は必須入力です"
      oh_no:   "はオーノーです"
    rules:
      name:    "名称"
```
Invoke with(error in params)
```
MyContract::new.(name: '').errors(full: true).to_h
```
expected_result: {:name=>["名称は必須入力です"]} (no whitespace between '名称' and 'は')
actual_result: {:name=>["名称 は必須入力です"]} (whitespace inserted)

Invoke with(error in rule)
```
MyContract::new.(name: 'oh no').errors(full: true).to_h
```
expected_result: {:name=>["名称はオーノーです"]} (no whitespace between '名称' and 'は')
actual_result: {:name=>["名称 はオーノーです"]} (whitespace inserted)

**Comment by solnic** [comment]
I moved this over here and marked it as a feature, because it's essentially a missing ability to configure behavior of "full messages" (whether a space should be used or not).

**Comment by cmcolinh** [comment]
I was sort of suspecting it would be as such, the best way to implement this does not immediately come to mind. Possibly by adding some key to the config object perhaps.  I could see something perhaps like
```
config.full_messages_whitespace[:ja] = false
```
But even that doesn't seem so self-documenting (also, that would be unwieldy in the source code in question)
e.g. (I'm not sure I have this right at all)
```
"#{messages.rule(rule, options) || rule}#{' ' unless config.full_messages_whitespace[options.locale].eql?(false)}#{text}"
```

**Comment by solnic** [comment]
We just need handlers for each locale identifier, with a default one that does what we already have, and the special one for `:ja`. Then we can do:

```ruby
full_text_handlers[locale].call(rule, options)
```

This can be as simple as a hash with a default value set.

**Comment by cmcolinh** [comment]
Would the handler be passed in as an injectable dependency?

e.g
option full_text_handlers, default: ->{Hash.new{|locale| ->(messages, rule, options){"#{messages.rule(rule, options) || rule} #{text}"}}} (basically the same as lib/dry/schema/message_compiler.rb line 185)
(ignoring for now that this would be an intolerable 137 characters in length)

Am I on the right track at all?

**Comment by solnic** [comment]
@cmcolinh I would just define them in a similar way like [predicate resolvers are set up](https://github.com/dry-rb/dry-schema/blob/master/lib/dry/schema/message_compiler.rb#L18-L28)
