### ISSUE TITLE
Can't define array of hashes with predicates

### ISSUE THREAD

**Issue by jlebray** [dry-rb/dry-schema#167]
Hi,

**Describe the bug**

We can't define arrays of hashes while adding predicates to the array.

**To Reproduce**

Following the [API documentation](https://www.rubydoc.info/gems/dry-schema/Dry/Schema/Macros/DSL) to define an array of hashes:
```ruby
# ----------
# This works
# ----------
schema = Dry::Schema.define do
  required(:tags).array(:hash) do
    required(:name).filled(:string)
  end
end

schema.call(tags: [{name: "John"}])
# => #<Dry::Schema::Result{:tags=>[{:name=>"aaa"}]} errors={}>

# ----------
# When adding a min_size predicate, thus using the alternate syntax
# ----------
schema = Dry::Schema.define do
  required(:tags).value(:array, min_size?: 1).each(:hash) do
    required(:name).filled(:string)
  end
end

schema.call(tags: [{name: "John"}])
# => NoMethodError: undefined method `required'

# ----------
# I tried adding `.schema` but it is still failing
# ----------
schema = Dry::Schema.define do
  required(:tags).value(:array, min_size?: 1).each(:hash).schema do
    required(:name).filled(:string)
  end
end

schema.call(tags: [{name: "John"}])
# => NoMethodError: undefined method `key?' for [{:name=>"John"}]:Array

```

**Expected behavior**

The second version, following the API documentation, should not error and allow the validation of the nested object.

**Your environment**

- Affects my production application: No
- Ruby version: 2.5.3
- OS: MacOS Mojave 10.14.3

**Comment by flash-gordon** [comment]
We could improve our docs on the subject.
`array(:hash) {` is a shortcut for `array { hash {`, `each` doesn't have support for this shortcut since it's rarely used. 

```ruby
schema = Dry::Schema.define do
  required(:tags).value(:array, min_size?: 1).each do
    hash do
      required(:name).filled(:string)
    end
  end
end
```
Please use our forum or chat for this sort of questions.

**Comment by solnic** [comment]
I suppose we could make this work:

```ruby
schema = Dry::Schema.define do
  required(:tags).array(:hash, min_size?: 1)do
    required(:name).filled(:string)
  end
end
```

WDYT?

**Comment by flash-gordon** [comment]
looks nice, are there any caveats?

**Comment by solnic** [comment]
ah sorry, it actually applies these predicates to the hashes (which makes sense). So we need to come up with a different shortcut.
