### ISSUE TITLE
Validation rules treat Types.Constructor(Array) and Types::Array.constructor differently

### ISSUE THREAD

**Issue by shepmaster** [dry-rb/dry-schema#171]
**Describe the bug**

Types created with `Types.Constructor(Array)` behave differently from those created with `Types::Array.constructor` when used with `.each`

**To Reproduce**

```ruby
# frozen_string_literal: true

require 'dry-schema'

module Types
  include Dry.Types()
end

SortString = Types.Constructor(Array) do |values|
  values.split(',').map do |s|
    by, dir = s.split(':', 2)
    { by: by.to_sym, dir: dir.to_sym }
  end
end

schema = Dry::Schema.Params do
  VALID_SORTS = %i[name date].freeze
  VALID_SORT_DIRECTIONS = %i[asc desc].freeze

  optional(:sorts).value(SortString).each do
    hash do
      required(:by).value(included_in?: VALID_SORTS)
      required(:dir).value(included_in?: VALID_SORT_DIRECTIONS)
    end
  end
end

puts schema.('sorts' => 'name:asc,date:desc').inspect
```

**Expected behavior**

`:sorts` would be an array of hashes.

**Actual behavior**

It fails validation:

```
[{:by=>:name, :dir=>:asc}, {:by=>:date, :dir=>:desc}]
#<Dry::Schema::Result{:sorts=>"name:asc,date:desc"} errors={:sorts=>["must be an array"]}>
```

**Your environment**

- Affects my production application: NO
- dry-validation version: 1.1.1
- Ruby version: 2.6.2
- OS: macOS

**Comment by flash-gordon** [comment]
@solnic yep! Last time I stopped around this place observing some unexpected output produced by dry-types schemas

**Comment by solnic** [comment]
@flash-gordon looks like `each` + block overrides custom type, if you remove `.each` part it will work

**Comment by solnic** [comment]
Gotcha:

```ruby
(byebug) Types::Array.constructor(&:to_a).respond_to?(:of)
true

(byebug) Types.Constructor(Array, &:to_a).respond_to?(:of)
false
```

which causes `hash` macro to fail to set the schema properly
