### ISSUE TITLE
required(:title) presence check does not work as advertised

### ISSUE THREAD

**Issue by ZASMan** [dry-rb/dry-schema#175]
According to your API, the following should validate the presence of an object:

However, I get the following error:

```
module MyModule
  class CreateParamsValidator < ::MyCustomBaseParamsValidator
    define do
      required(:title).filled(:str?)
````

```
 #<Dry::Schema::Result{} errors={:title=>["is missing"]}>
```

I'm curious, has the API changed but not the documentation?

**Comment by timriley** [comment]
Could you please share a full example to reproduce this issue? It’s hard to ascertain where a fault may lie from your short snippets. Thanks!

**Comment by flash-gordon** [comment]
Please provide a full reproducible example.

**Comment by ZASMan** [comment]
Hello, I was able to figure it out. Problem was I needed to do `to_h`. Thank you `params.require("data").permit!.to_h`
