### ISSUE TITLE
maybe(array[:integer]) doesn't expand to each { int? }

### ISSUE THREAD

**Issue by pabloh** [dry-rb/dry-schema#206]
The following code does not behaves as expected when using `maybe`:

```ruby
schema = Dry::Schema.Params do
  required(:ids).maybe(array[:integer])
end # rules={:ids=>"key?(:ids) AND key[ids](not(nil?) THEN array?)"}

schema.call({}).success? # true
schema.call({id: ['3']}).success? # true
schema.call({{id: ['blah']}}).success? # true BUT SHOULD BE FALSE
```

but if you use `value` instead:

```ruby
schema = Dry::Schema.Params do
  required(:ids).value(array[:integer])
end # rules={:ids=>"key?(:ids) AND key[ids](array? AND each(int?))"}

schema.call({}).success? # false
schema.call({id: ['3']}).success? # true
schema.call({{id: ['blah']}}).success? # false
```

Apparently when using `maybe` the `each(int?)` expansion is lost.

- Affects my production application: YES
- Ruby version: 2.6.5
- OS: Linux 4.10.0-42-generic #46-Ubuntu SMP x86_64 GNU/Linux

**Comment by solnic** [comment]
Thanks for reporting this. I'll fix it in the next patch release.

**Comment by pabloh** [comment]
I investigated a bit more and this seems to happen on sum types as well:

```
schema1 = Dry::Schema.Params do
   required(:ids).filled([array[:integer], :integer])
end

schema1.call({ids: '7'}).success? # true
schema1.call({ids: 'blah'}).success? # false
schema1.call({ids: ['3']}).success? # true
schema1.call({ids: ['blah']}).success? # true **but should be false**


schema2 = Dry::Schema.Params do
   required(:ids).value([array[:integer], :nil])
end

schema2.call({ids: nil}).success? # true
schema2.call({ids: ['3']}).success? # true
schema2.call({ids: ['blah']}).success? # true **but should be false**
```

**Comment by pabloh** [comment]
> ```ruby
> schema2 = Dry::Schema.Params do
>    required(:ids).value([array[:integer], :nil])
> end
> 
> schema2.call({ids: nil}).success? # true
> schema2.call({ids: ['3']}).success? # true
> schema2.call({ids: ['blah']}).success? # true BUT SHOULD BE FALSE
> ```

I'll open a new PR for this case.
