### ISSUE TITLE
Type coercion doesn't work on schemas nested inside an array

### ISSUE THREAD

**Issue by pabloh** [dry-rb/dry-schema#207]
When you have the following nested schema inside an array, type coercion only work for the outer field but not for the inner one:
```ruby
schema = Dry::Schema.Params do
  required(:id).value(:integer)
  required(:hashes).each do
    schema do
      required(:inner_id).value(:integer)
    end
  end
end

schema.call({id: '23', hashes: [{ inner_id: 452 }] })
# => #<Dry::Schema::Result{:id=>23, :hashes=>[{:inner_id=>452}]} errors={}>>

schema.call({id: '23', hashes: [{ inner_id: '452' }] })
# => #<Dry::Schema::Result{:id=>23, :hashes=>[{:inner_id=>"452"}]} errors={:hashes=>{0=>{:inner_id=>["must be an integer"]}}}>
```
I can't explain what's going on here.

The problem does not seems to manifest is there's no array in the middle:
```ruby
schema = Dry::Schema.Params do
  required(:id).value(:integer)
  required(:hash).schema do
    required(:inner_id).value(:integer)
  end
end

schema.call({id: '23', hash: { inner_id: '452' } })
# => #<Dry::Schema::Result{:id=>23, :hash=>{:inner_id=>452}} errors={}
```

- Affects my production application: YES
- Ruby version: 2.6.5
- OS: Linux 4.10.0-42-generic #46-Ubuntu SMP x86_64 GNU/Linux

**Comment by flash-gordon** [comment]
Your schema is incorrect because it's missing an array type. This one works:

```ruby

schema = Dry::Schema.Params do
  required(:id).value(:integer)
  required(:hashes).array(:hash) do
    required(:inner_id).value(:integer)
  end
end
```
`.array` above includes both the type and the `each` predicate.
Docs have examples: https://dry-rb.org/gems/dry-schema/1.4/nested-data/#nested-code-array-code

**Comment by pabloh** [comment]
Oh, sorry for the noise, thanks!

**Comment by flash-gordon** [comment]
Np. It's used to work differently in pre-1.0 so it's a common "trap". It seems to work at the beginning, but it actually doesn't. And you only know when you pass invalid input 🤷‍♂
