### ISSUE TITLE
`value(:hash)` and `maybe(:hash)` should expose schema DSL

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-schema#215]
`value(:hash) do ... end` and `maybe(:hash) do ... end` should expose nested schema DSL just like `array(:hash)` does. This reduces nesting and is nicer to read.

```ruby
# this
value do
  hash do
    # ...
  end
end

# could be this
value(:hash) do
  # ...
end
```

**Comment by waiting-for-dev** [comment]
Both

```ruby
required(:info).value(:hash) do
  required(:name).value(:string)
end
```

and

```ruby
required(:info).maybe(:hash) do
  required(:name).value(:string)
end
```

raise `NoMethodError` for `Dry::Schema::Macros::Value`. However, you can both do:

```ruby
required(:info).value do
  hash do
    required(:name).value(:string)
  end
end
```

and 

```ruby
required(:info).maybe do
  hash do
    required(:name).value(:string)
  end
end
```

Isn't it correct?

**Comment by solnic** [comment]
@waiting-for-dev OK sorry my bad. I confused it with `array(:hash) do .. end` shortcut which does work. I updated title/description/labels (coz it's not really a bug anymore).

**Comment by waiting-for-dev** [comment]
Hey @solnic , wouldn't it be a bit confusing (or complex at the source code level) mixing schema DSL context with predicate definition context? I mean, currently it's already possible to provide a block to the `value` macro in order to define predicates:

```ruby
required(:name).value { str? }
```

**Comment by waiting-for-dev** [comment]
I wanted to play with it so I went ahead and submitted the referenced PR, but feel free to reject it if you change your mind according to previous comment :sweat_smile:

**Comment by flash-gordon** [comment]
@waiting-for-dev hashes (as dictionaries or maps) are so common for schemas that I'm sure we can sacrifice some purity of the sources as we already did for `array(:hash)`. Moreover, differences between `array` and `maybe`/`value` create confusion.

**Comment by solnic** [comment]
> Hey @solnic , wouldn't it be a bit confusing (...)

@waiting-for-dev I actually think it's gonna be less confusing, otherwise people may end up with weird stuff like `value(:hash) { str? }` which translates to `value { hash? & str? }` which makes no sense.
