### ISSUE TITLE
Unexpected string coercion with 'maybe(:sting)'

### ISSUE THREAD

**Issue by sd-kin** [dry-rb/dry-schema#227]
With schema

```ruby
schema = Dry::Schema.Params do
  required(:name).value(:string)
  required(:surname).maybe(:string)
end
```
I try to validate

```ruby
schema.call(name: '', surname: '')
```

and get result

```ruby
#<Dry::Schema::Result{:name=>"", :surname=>nil} errors={}>
```

Empty string in `:surname` coerced to `nil`. Although  value is optional and can be `nil` I expect to get back empty string when I give empty string, just like it work with required value in `:name`.

**Your environment**

- Affects my production application: **NO**
- Ruby version: ruby 2.6.1p33
- OS: Mojave 10.14.3
- dry-schema 1.4.3
- dry-types 1.2.2

**Comment by flash-gordon** [comment]
This is documented behavior https://dry-rb.org/gems/dry-schema/1.4/params/#handling-empty-strings Use `value` if you need empty strings. The problem is url-encoded params can only pass strings.
