### ISSUE TITLE
JSON schema coercing empty string to nil

### ISSUE THREAD

**Issue by RobinClowers** [dry-rb/dry-schema#229]
Using the json schema, empty strings are being coerced to nil.

 ```ruby
class MyContact < Dry::Validation::Contract
  json do
    optional(:value).maybe(:string)
  end
end

MyContract.new.call({ value: '' })
#<Dry::Validation::Result{:value=>nil} errors={}>
```

Since this is an optional maybe string, it should not coerce to nil.

    Affects my production application: NO
    Ruby version: 2.6.2
    OS: MacOS 10.15.2

**Comment by solnic** [comment]
@RobinClowers good catch! I moved it to dry-schema and it'll be fixed here. In general *everything* that happens within `json`, `params` and `schema` blocks in dry-validation is handled 100% by dry-schema.

**Comment by rawburt** [comment]
This seems to be unique to the `JSON` processor:

```ruby
schema_json = Dry::Schema.JSON do
  optional(:value).maybe(:string)
end

schema_json.call(value: '')
#<Dry::Schema::Result{:value=>nil} errors={}>

schema = Dry::Schema.define do
  optional(:value).maybe(:string)
end

schema.call(value: '')
#<Dry::Schema::Result{:value=>""} errors={}>
```

**Comment by flash-gordon** [comment]
@rawburt it works (and should work) this way with `Params` too

**Comment by solnic** [comment]
yeah plain schema has no coercions, that's why there's a difference in behavior

**Comment by solnic** [comment]
I *guess* the solution would be to check in `maybe` if the type spec points to a `str?` predicate, and if yes, then the type should be set to the nominal string, instead of params string.

**Comment by solnic** [comment]
It turned out this is coercion behavior from dry-types so it should be fixed there:

```ruby
(byebug) type_registry[:nil]
#<Dry::Types[Constructor<Nominal<NilClass> fn=Dry::Types::Coercions::JSON.to_nil>]>
(byebug) type_registry[:nil]['']
nil
```

**Comment by flash-gordon** [comment]
ref https://github.com/dry-rb/dry-types/issues/396
