### ISSUE TITLE
Class-level schema config is not an instance of Dry::Schema::Config

### ISSUE THREAD

**Issue by robhanlon22** [dry-rb/dry-schema#240]
The documentation shows that one can create a custom schema base class and apply configuration to it: https://dry-rb.org/gems/dry-schema/1.4/basics/working-with-schemas/#defining-base-schema-class It looks like something changed at some point, so the class-level config within an instance of `Dry::Schema::Processor` is no longer a `Dry::Schema::Config`, so the documentation example does not work.

**To Reproduce**

```ruby
# example.rb

require "dry-schema"

class AppSchema < Dry::Schema::Params
  config.messages.load_paths << '/my/app/config/locales/en.yml'
  config.messages.backend = :i18n

  define do
    # define common rules, if any
  end
end
```

```bash
$ ruby example.rb
Traceback (most recent call last):
	1: from example.rb:3:in `<main>'
example.rb:4:in `<class:AppSchema>': undefined method `messages' for #<#<Class:0x00007fdf4a1067e8>:0x00007fdf4a1065b8> (NoMethodError)
```

**Expected behavior**

Processor subclasses should be able to have access to the same configuration as their instances.

**Your environment**

- Affects my production application: NO
- Ruby version: 2.7.0
- OS: macOS 10.14.6

**Comment by solnic** [comment]
oh wow this is me failing to port dry-validation docs :( this is indeed no longer possible since `Params` is now a `Processor` subclass which has its own config. I guess we should use `Dry::Schema::Config` as the base for `Processor` config, and then it should copy it to its underlying DSL.
