### ISSUE TITLE
Short way of building optional types

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-schema#28]
Things like `[:nil, :string]` can lead to confusion when we're dealing with coercible types. Changing the order changes the semantics though for sum types, in general, the semantics remains intact. I think we could have a means for building optional types in a similar way do it for arrays atm:

```ruby
optional(:foos).value(array[:integer])
optional(:bar).value(optional[:string])
```
The biggest problem here is coming up with naming 😟 Overloading `optional` doesn't look nice.

**Comment by flash-gordon** [comment]
Also see https://github.com/dry-rb/dry-validation/issues/376

**Comment by Morozzzko** [comment]
Would `nullable` be appropriate here? Even though Ruby has `nil` instead of `null`, `nullable` seems to be widely accepted by programmers

**Comment by solnic** [comment]
We already have that, just use `maybe`:

``` ruby
optional(:foos).maybe(array[:integer])
optional(:bar).maybe(:string)
```

This should be enough, no?

**Comment by flash-gordon** [comment]
@solnic it should, I was overconcentrating on types. It's a bit inconsistent with how arrays types are built, though. Type builders seem more flexible. Should we support both?

**Comment by solnic** [comment]
Yes I planned to extend type builder api, array method was just the beginning.

**Comment by flash-gordon** [comment]
k, I renamed the issue :)

**Comment by solnic** [comment]
Given that I'll add support for type specs in `each` macro, and that you can use `maybe` to shorten optional specs, I'm not entirely sure if anything more needs to be done. See, this is or will be possible:

``` ruby
required(:foo).maybe(:string)

required(:foo).maybe(array[:integer])

required(:foo).maybe(:array).each(:integer) # support coming soon
```

Personally I prefer this style more than new methods for optional values, see:

``` ruby
required(:foo).maybe(array[:integer])

# vs (regardless of the method name)

required(:foo).value(nullable(array[:integer])) # messy IMO
```

I'm postponing any potential work on this until after 1.0.0 release. We can discuss this further.

**Comment by solnic** [comment]
OK there's nothing else we need to do, using `maybe` is sufficient.
