### ISSUE TITLE
Nested optional params schemas don't accept string keys.

### ISSUE THREAD

**Issue by pat** [dry-rb/dry-schema#296]
When there's an optional hash/schema value for a params key, the expectation is that the nested hash's keys are symbols. Going by @solnic's comments in [this discussion](https://discourse.dry-rb.org/t/matching-optional-params-schema-against-a-nested-schema/1069/5), it sounds like a bug (and with my limited knowledge, I agree - especially given params data via HTTP requests is always going to be strings).

```ruby
require "dry/schema"

inner_schema = Dry::Schema.Params do
  required(:path).filled(:string)
end

outer_schema = Dry::Schema.Params do
  required(:foo).maybe(:hash, inner_schema)
end

# This works as expected
puts outer_schema.("foo" => {path: "bar"}).inspect
# => #<Dry::Schema::Result{:foo=>{:path=>"bar"}} errors={}>

# This fails :(
puts outer_schema.("foo" => {"path" => "bar"}).inspect
# => #<Dry::Schema::Result{:foo=>{"path"=>"bar"}} errors={:foo=>{:path=>["is missing"]}}>
```

From some quick testing, this only appears to be a bug for optional values (`maybe`). Using `hash(inner_schema)` and `filled(inner_schema)` both return no validation errors for both symbol and string keys.

My testing for this has been on macOS with MRI 2.6.6, I've not attempted it in production on Linux, but I doubt it's environment-specific.

**Comment by solnic** [comment]
For the record, this works:

```ruby
# frozen_string_literal: true

require "dry/schema"

inner_schema = Dry::Schema.Params do
  required(:path).filled(:string)
end

outer_schema = Dry::Schema.Params do
  required(:foo).hash(inner_schema)
end

# This works as expected
puts outer_schema.("foo" => {path: "bar"}).inspect
# => #<Dry::Schema::Result{:foo=>{:path=>"bar"}} errors={}>

# This fails :(
puts outer_schema.("foo" => {"path" => "bar"}).inspect
```
