### ISSUE TITLE
Rules from enum types aren't checked

### ISSUE THREAD

**Issue by stefkin** [dry-rb/dry-schema#30]
Enum validation from dry-types doesn't seem to work with type_specs

```
require 'dry-types'
require 'dry-validation'

State = Dry::Types['strict.string'].enum('enabled', 'disabled')

schema = Dry::Validation.Form do
  configure { config.type_specs = true }

  required(:state, State).filled
end

schema.(state: "enabled").errors
=> {}
schema.(state: "foo").errors
=> {:state=>["must be one of: enabled, disabled"]}
```

Please note that It works as described in: https://github.com/dry-rb/dry-validation/issues/348

for example `required(:state).filled(State)` makes the above example work properly

**Comment by Bugagazavr** [comment]
Looks like this is still actual for 1.1.0

https://gist.github.com/Bugagazavr/9294c8318d5018d7e9b11cab61962d16

**Comment by solnic** [comment]
Constrained types are not supported yet, that's why this issue is still open.

**Comment by solnic** [comment]
This now works starting from 1.3.0
