### ISSUE TITLE
"is not allowed" raised when `validate_keys` is enabled for maybe hashes

### ISSUE THREAD

**Issue by svobom57** [dry-rb/dry-schema#308]
**Describe the bug**
I think I ran into a bug with `validate_keys` feature. Suppose we have the following schema:
```ruby
schema = Dry::Schema.Params do
  config.validate_keys = true
  
  required(:locations).array(:hash) do
    required(:feedback_location).maybe(:hash) do
      required(:lat).filled(:float)
      required(:lon).filled(:float)
    end
  end
end

schema.call({ locations: [{ feedback_location: nil }] }).errors
=> #<Dry::Schema::MessageSet messages=[#<Dry::Schema::Message text="is not allowed" path=[:locations, 0, :feedback_location] predicate=nil input={:locations=>[{:feedback_location=>nil}]}>] options={:failures=>true}>
```
however, when we amend the schema not to `validate_keys` we won't get any errors:
```ruby
schema = Dry::Schema.Params do
  required(:locations).array(:hash) do
    required(:feedback_location).maybe(:hash) do
      required(:lat).filled(:float)
      required(:lon).filled(:float)
    end
  end
end

schema.call({ locations: [{ feedback_location: nil }] }).errors
=>  #<Dry::Schema::MessageSet messages=[] options={}>
```
Why would I get the `is not allowed` message when the `feedback_location` is specified as a `maybe` value hash when the `validate_keys` is enabled?

**Expected behavior**
The schema should pass as the `feedback_location` is defined in the schema as a `maybe` value hence the `validate_keys` should not error out.

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.7
- dry-schema (1.5.2)
dry-validation (1.5.3)
- OS: MacOS

**Comment by svobom57** [comment]
@solnic The nested problem is gone in `1.5.3` but I think there's a very similar issue with non-nested structures still 😢 :

```ruby
schema = Dry::Schema.Params do
  config.validate_keys = true

  required(:feedback_location).maybe(:hash) do
    required(:lat).filled(:float)
    required(:lon).filled(:float)
  end
end

schema.call({ feedback_location: nil }).errors
=> #<Dry::Schema::MessageSet messages=[#<Dry::Schema::Message text="is not allowed" path="feedback_location" predicate=nil input={:feedback_location=>nil}>] options={:failures=>true}>
```

**Comment by solnic** [comment]
@svobom57 would you mind reporting a new issue about it? It'll be easier to track it like that

**Comment by svobom57** [comment]
@solnic Will do 👍
