### ISSUE TITLE
Key coercing in Each works only if you set array type spec

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-schema#31]
This form schema has `.each` right after `required`

```ruby
schema = Dry::Schema.Form do
  required(:foo).each do
    schema do
      required(:bar).filled(:string)
    end
  end
end
```

and it rejects valid input
```ruby
2.6.1 :001 > schema.("foo" => ["bar" => "baz"])
 => #<Dry::Schema::Result{:foo=>[{"bar"=>"baz"}]} errors={:foo=>{0=>{:bar=>["is missing"]}}}> 
```

At the same time

```ruby
schema = Dry::Schema.Form do
  required(:foo).value(:array).each do
    schema do
      required(:bar).filled(:string)
    end
  end
end
```

works 👌 

```
2.6.1 :001 > schema.("foo" => ["bar" => "baz"])
 => #<Dry::Schema::Result{:foo=>[{:bar=>"baz"}]} errors={}> 
```

The fact it silently doesn't work is surprising.

**Comment by solnic** [comment]
Nice catch. I actually don't know if we want `each` to automatically add `array` type-spec. It turned out to be problematic in some cases. ie you want to check if an array has a min size and then check its elements.

**Comment by flash-gordon** [comment]
The question is more about making it predictable. We can throw an error on `.each` if the type spec is not of the array "kind"

**Comment by solnic** [comment]
@flash-gordon that would be an improvement, but my question is still relevant - do we want `each` to auto-add `array` type-spec or not. ie `schema` *does add `hash` type-spec* which means that `each` is not consistent here; the trick is that we also need something like each but w/o the type spec.

**Comment by flash-gordon** [comment]
then how about adding `.array do` and `.hash do`?

**Comment by solnic** [comment]
@flash-gordon this is exactly what I was thinking about, but the question is how you provide predicates for the value vs the elements? 😄

**Comment by flash-gordon** [comment]
@solnic don't really get it, `array` and `hash` accept value predicates and a block for elements. How about that?

**Comment by solnic** [comment]
@flash-gordon I like the fact you can do `each(:int?)` vs `array { int? }`, it's shorter and nicer

**Comment by flash-gordon** [comment]
you still can use `each` then: `array(array_type).each(:int?)`. Also, this is a lesser problem for `hash` I guess

**Comment by solnic** [comment]
@flash-gordon but this will apply `array?` twice, which I consider to be a problem

**Comment by flash-gordon** [comment]
@solnic ah, no, I meant to leave `each` as it is, w/o adding array spec internally

**Comment by flash-gordon** [comment]
and then we can change `schema` in that direction instead, wdyt? Just an idea

**Comment by solnic** [comment]
@flash-gordon so you want to remove `hash?` check from `schema` and add `hash do ...end` syntax for cases where you want both `hash?` check and a block with a nested schema?

**Comment by flash-gordon** [comment]
@solnic yes, precisely
