### ISSUE TITLE
"is not allowed" raised when `validate_keys` is enabled for maybe hashes

### ISSUE THREAD

**Issue by svobom57** [dry-rb/dry-schema#311]
**Describe the bug**
There was an issue: https://github.com/dry-rb/dry-schema/issues/308 whereby the validation of keys for nested maybe hashes weren't working prior to version `1.5.3`. There's still an issue with non-nested maybe hashes.

**To Reproduce**
```ruby
schema = Dry::Schema.Params do
  config.validate_keys = true

  required(:feedback_location).maybe(:hash) do
    required(:lat).filled(:float)
    required(:lon).filled(:float)
  end
end

schema.call({ feedback_location: nil }).errors
=> #<Dry::Schema::MessageSet messages=[#<Dry::Schema::Message text="is not allowed" path="feedback_location" predicate=nil input={:feedback_location=>nil}>] options={:failures=>true}>
```

**Expected behaviour**

It shouldn't have an error since the `feedback_location` field is a `maybe` hash.

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.7
- dry-schema (1.5.3)
dry-validation (1.5.3)
- OS: MacOS

**Comment by svobom57** [comment]
@solnic When are you planning on cutting the `1.5.4` release?

**Comment by solnic** [comment]
Tomorrow
