### ISSUE TITLE
Coercible integer doesn't accept Number as String, but accepts Number.

### ISSUE THREAD

**Issue by artur-siupik** [dry-rb/dry-schema#324]
**Describe the bug**

Coercible integer can accept number input `200.1` but doesn't accept Number as String `"200.1"`.

**To Reproduce**

This returns error:

```ruby
Types::Coercible::Integer["100.0"]
# invalid value for Integer(): "100.0"
```

This works:

```ruby
Types::Coercible::Integer[100.0]
# 100
```

**Expected behavior**

```ruby
Types::Coercible::Integer["100.0"]
# 100
```

**Comment by flash-gordon** [comment]
`Coercible` types use builtin Ruby methods for coercion. `Types::Coercible::Integer` delegates to `Kernel.Integer` so it's a question to Ruby design, more or less. In general, dry-types doesn't treat non-integer strings as integers, this is probably for the best. You can write a custom type with `Types::Coercible::Integer.prepend { _1.sub(/\.0/, '') }`.

P.S. This is an issue for the dry-types repo, not dry-schema.

**Comment by artur-siupik** [comment]
Thanks for the explanation!
