### ISSUE TITLE
Generating errors for unexpected keys in Hash

### ISSUE THREAD

**Issue by backus** [dry-rb/dry-schema#35]
I would love to be able to define a schema which generated errors if it was given unexpected keys:

``` ruby
require 'dry/validation'

schema = Dry::Validation.Schema(strict: true) do
  hash? do
    required(:foo).filled(:int?)
    required(:bar).filled(:str?)
  end
end

outcome = schema.call(foo: 1, bar: "two", baz: 3.0)
p outcome.messages # => {:baz=>["is not allowed"]}
```

This is really important for defining a public JSON API where you want to reject invalid user input.

**Comment by joelvh** [comment]
Will `Schema#strict` be implemented in dry-validation v1.0.0 Contract as a feature, or do we need to key into the underlying schema?

**Comment by solnic** [comment]
@joelvh I'd prefer to have it as part of dry-schema but we'll see what makes more sense.

**Comment by joelvh** [comment]
@solnic that was quick! I just realized that `Schema#strict` is in dry-types, which dry-schema and dry-validation don't (?) use under the hood?

Lots of things to reconcile getting things upgraded to v1.0.0 - happy to see many of the changes!

**Comment by solnic** [comment]
> @solnic that was quick!

You commented while I was going through my inbox 😄 

> I just realized that Schema#strict is in dry-types, which dry-schema and dry-validation don't (?) use under the hood?

Strict hash schemas from dry-types are not used at all by dry-schema/validation. In order to validate input's keys, we need support for "base" errors. This was added to dry-validation so now dry-schema needs to catch up.

> Lots of things to reconcile getting things upgraded to v1.0.0 - happy to see many of the changes!

Yes it's **a big** step forward with dry-types/logic/schema/validation reaching 1.0.0 😄

**Comment by jacek213** [comment]
Still not supported in 1.4?

**Comment by solnic** [comment]
@jacek213 yes, it's not yet supported
