### ISSUE TITLE
Each schema hold it's own copy of all the validation strings

### ISSUE THREAD

**Issue by casperisfine** [dry-rb/dry-schema#352]
## Describe the bug

Each schema instance load it's own version of the validations strings. It's both a waste of CPU during the application boot as the file has to be parsed repeatedly, and a waste of RAM.

Here's a heap-profiler report:

```
   2.48 kB      62  "must be odd"
                62  msgpack-1.4.2/lib/msgpack/factory.rb:70
 
   2.48 kB      62  "must be filled"
                61  msgpack-1.4.2/lib/msgpack/factory.rb:70
                 1  bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:19
 
   2.48 kB      62  "must be even"
                62  msgpack-1.4.2/lib/msgpack/factory.rb:70
 
   2.48 kB      62  "must be boolean"
                61  msgpack-1.4.2/lib/msgpack/factory.rb:70
                 1  bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:19
 
   2.48 kB      62  "must be an integer"
                61  msgpack-1.4.2/lib/msgpack/factory.rb:70
                 1  bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:19
 
   2.48 kB      62  "must be an array"
                61  msgpack-1.4.2/lib/msgpack/factory.rb:70
                 1  bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:19
 
   2.48 kB      62  "must be a string"
                61  msgpack-1.4.2/lib/msgpack/factory.rb:70
                 1  bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:19
 
   2.48 kB      62  "must be a float"
                61  msgpack-1.4.2/lib/msgpack/factory.rb:70
                 1  bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:19
```

These strings are reported as created by messagepack because of Bootsnap's YAML precompilation cache, but I tracked them down to `dry-schema`. From this extract you can likely guess that we have 61 schemas.

## To Reproduce

Simply creating multiple schema in the same process should exhibit the behavior.

## Expected behavior

I would expect schemas to somehow have a mechanism to re-use already loaded error messages.

Or at the very least, `dry-schema` could pass `freeze: true` to `YAML.load_file` so that the strings would be deduplicated.

**Comment by solnic** [comment]
Great catch. We could easily cache it [right here](https://github.com/dry-rb/dry-schema/blob/d391e78c254b26ba6c7f8538cf84fc219a0e0ead/lib/dry/schema/messages/yaml.rb#L182).
