### ISSUE TITLE
Validating Array of hashes coerces non-hash elements to empty hashed, doesn't return an error if a given element of the array is not a hash

### ISSUE THREAD

**Issue by TimoMoss** [dry-rb/dry-schema#368]
## Describe the bug
Hello, I'm using dry-schema (1.6.0)  as a dependency of  dry-validation (1.6.0)

## To Reproduce
```
class ValidateParams < Dry::Validation::Contract
  shema do
    required(:limits).array(:hash) do
        optional(:value).filled(:string)
    end
  end
end
```
## Expected behavior
`validation = ValidateParams.new.call({limits: [1]}) `
I expect that `validation.errors.to_h` returns some error message about 1 must be a hash or so, but I don't get any errors.
`validation.to_h`  returns  `{:limits=>[{}]}` 

is it the expected behavior and if so, how can I restrict to return an error if the type of validated elements is not a hash?

## My environment

- Affects my production application: **NO**
- Ruby version: ruby '2.5.7'
- OS: Mac OS Catalina

**Comment by ojab** [comment]
Looks like https://github.com/dry-rb/dry-schema/pull/354, please retest with dry-schema-1.7.0.

**Comment by ojab** [comment]
https://github.com/dry-rb/dry-schema/commit/d7203457bfe7f5e1d751ef9f3f8e454abb7ce828 @ https://github.com/dry-rb/dry-schema/commit/d7203457bfe7f5e1d751ef9f3f8e454abb7ce828.patch
Monkeypatching `Dry::Schema::Key::Array#write` should be enough.

**Comment by TimoMoss** [comment]
@ojab it helped, thank you!
