### ISSUE TITLE
The unexpected behavior of the validation of object with array type attribute that contains custom object

### ISSUE THREAD

**Issue by dawlib** [dry-rb/dry-schema#379]
## Describe the bug

The unexpected behavior of the validation is shown in the example below.

## To Reproduce

```ruby
require 'dry/schema'

module Types
  include Dry::Types()
end

class MyItem < Dry::Schema::JSON
  define do
    required(:name).filled(Types::String.enum(*%w[b]))
    optional(:time).filled(:time)
  end
end

class MyList < Dry::Schema::JSON
  define do
    required(:list).value(:array).each { MyItem.new }
  end
end

item = { 'name' => 'b', 'time' => Time.now.iso8601 }

MyItem.new.call(item).failure? # => false
MyList.new.call('list' => [item]).failure? # => true

MyList.new.call('list' => [item])
# => #<Dry::Schema::Result{:list=>[{"name"=>"b", "time"=>"2021-11-16T14:14:18+01:00"}]} errors={:list=>{0=>{:name=>["is missing"]}}} path=[]>
```

## Expected behavior

I would expect to receive `false` as a result of the command below:
```ruby
puts MyList.new.call('list' => [item]).failure? # => false
```

## My environment

- Affects my production application: **YES**
- dry-schema version: `1.8.0`
- Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`
- OS: `macOS Monetery 12.0.1`, Ubuntu 18.04

**Comment by flash-gordon** [comment]
@dawlib is syntax like `.each { MyItem.new }` described somewhere? Looks unfamiliar

**Comment by madejejej** [comment]
@flash-gordon not per-se `.each { MyItem.new }`, but a similar syntax is described in one of the examples here https://dry-rb.org/gems/dry-schema/1.5/nested-data/#nested-code-array-code 

```ruby
schema = Dry::Schema.Params do
  required(:people).value(:array, min_size?: 1).each do
    hash do
      required(:name).filled(:string)
      required(:age).filled(:integer, gteq?: 18)
    end
  end
end

errors = schema.call(people: []).errors

puts errors.to_h.inspect
# => {
#   :people=>["size cannot be less than 1"]
# }
```

**Comment by esparta** [comment]
IMO even tho looks similar it's not, @madejejej

The DSL on the example is calling an _internal_ procedure on every element of the array and interpreted as that, in your case the `.each { MyItem.new } ` is just yielding an object tha - as the current behavior of the DS- is not interpreted as such. Looks like a new feature the maintainers would need to be agree on incorporate  - and support.

It would be nice to pitch the idea in the Dry-rb forums.

**Comment by flash-gordon** [comment]
It's a misuse of the API, it shouldn't have worked in the first place. You already can share schemas, just don't use blocks

```ruby
class MyItem < Dry::Schema::Params
  define do
    required(:name).filled(Types::String.enum(*%w[b]))
    optional(:time).filled(:time)
  end
end

class MyList < Dry::Schema::Params
  define do
    required(:list).value(:array).each(MyItem.new)
  end
end

item = { 'name' => 'b', 'time' => Time.now.iso8601 }

[1] pry(main)> MyList.new.call('list' => [item])
=> #<Dry::Schema::Result{:list=>[{:name=>"b", :time=>2021-12-01 15:41:25 +0300}]} errors={} path=[]>
```
