### ISSUE TITLE
Type coercion doesn't work

### ISSUE THREAD

**Issue by sdogruyol** [dry-rb/dry-schema#383]
## Describe the bug

Type coercion doesn't work for `Dry::Schema.Params`

## To Reproduce

```ruby
IndexSchema = Dry::Schema.Params do
  optional(:filter).hash do
    optional(:template).filled(:bool?)
  end
end
```

Here's the following error, template is not cast into boolean

```
<Dry::Schema::Result{filter=>{:template=>"true"}} errors={:filter=>{:template=>["must be boolean"]}} path=[]>
```

## Expected behavior

Type coercion should work by default

## My environment

- Affects my production application: **YES**
- Ruby version: 3.0.2
- OS: OS X 10.16 Big Sur

**Comment by flash-gordon** [comment]
`:bool?` is a predicate, it checks if the value is literally `true` or `false`. Type names don't end with a question mark:
```ruby
IndexSchema = Dry::Schema.Params do
  optional(:filter).hash do
    optional(:template).filled(:bool)
  end
end

dry-schema> IndexSchema.('filter' => { 'template' => 'true' })
# => #<Dry::Schema::Result{:filter=>{:template=>true}} errors={} path=[]>
```
