### ISSUE TITLE
Explicitly mark that a param can be ignored if nil

### ISSUE THREAD

**Issue by TiteiKo** [dry-rb/dry-schema#40]
Given there's a search form, where all fields are optional, and a validation schema that receives the form raw data via rack.

As we know, the form will be submitted with empty strings as values for empty fields.

Extremely simplified, the params could look something like:

``` ruby
Params = Dry::Validation.Form do
  optional(:date).maybe(:date?) # or required, as it's a form, it will be set anyway
end
```

So, when the form submits "" for the date param, the validation output will look like `{ date: nil }`, and we have to handle this nil value somewhere.

Is there any way to explicitly say that this param can be ignored if nil? Like "ok, I know it can be empty or nil, but if it is, please just don't put it in the output", so that the output would look like `{}` and we'd not have to handle the nil value elsewhere.

**Comment by waiting-for-dev** [comment]
@solnic I also need this feature. You said there is some infrastructure prepared. Is is still true for 1.0? Let me know if I can help with this issue.

**Comment by solnic** [comment]
@waiting-for-dev schemas are `Schema::Processor` sub-classes, when you apply a schema to an input what actually happens is that all the steps that a schema has configured will be applied one-by-one in the order they were added. By default [steps are configured like that](https://github.com/dry-rb/dry-schema/blob/master/lib/dry/schema/dsl.rb#L191-L197) based on whatever was defined within the DSL.

So, that's the infrastructure - step-based processors aka schemas. What we're missing is a way of configuring arbitrary steps, so that you could do...let's say this:

```ruby
class MySchema < Dry::Schema::Params
  define do
    required(:name).filled(:string)
  end

  after(:rule_applier) do |input|
    input.compact
  end
end
```

Does this make sense?

**Comment by solnic** [comment]
@waiting-for-dev one more thing - this needs to be cleaned up and promoted to a 1st-class API, right now `Processor` is a bit ugly (you'll see). We need explicit step definitions with unique names (there are built-in ones, like that `rule_applier` in the example above). Then we need a way to access them in a nicer way than doing silly things like `steps.detect { |s| s.is_a?(RuleApplier)`. So overall this requires some refactoring first.

**Comment by waiting-for-dev** [comment]
@solnic I'm afraid I'm a little lost with what is need to be done at first. Which kind of refactor `Processor` exactly  needs? From its docs:

```
    # Processing is split into 4 main steps:
    #
    #   1. Prepare input hash using a key map
    #   2. Apply pre-coercion filtering rules (optional step, used only when `filter` was used)
    #   3. Apply value coercions based on type specifications
    #   4. Apply rules
```

If steps are simply a stack of operations that should be applied one after the other, why do we need, in the first place, to access them in an isolated way?

**Comment by solnic** [comment]
> If steps are simply a stack of operations that should be applied one after the other, why do we need, in the first place, to access them in an isolated way?

because it's needed by the DSL when you define nested schemas.

**Comment by waiting-for-dev** [comment]
@solnic it can be closed by #40

Docs:

https://dry-rb.org/gems/dry-schema/1.4/advanced/processor-steps/

**Comment by waiting-for-dev** [comment]
Sorry, I meant #190 :)

**Comment by solnic** [comment]
Closing because it can be done via an after hook now:

```ruby
dry-schema> s = params do
dry-schema*>   before(:rule_applier) do |result|
dry-schema*>     result.replace(result.to_h.compact)
dry-schema*>   end  
dry-schema*>   
dry-schema*>   required(:name).filled(:string)
dry-schema*>   required(:age).maybe(:integer)
dry-schema*> end  
=> #<Dry::Schema::Params keys=["name", "age"] ... >
dry-schema> s.(name: "jane", age: "").to_h
=> {:name=>"jane"}
```
