### ISSUE TITLE
Loose generation fails for nested schema

### ISSUE THREAD

**Issue by xronos-i-am** [dry-rb/dry-schema#407]
## Describe the bug

In "loose" mode JSON schema should be generated. The following code throws `Dry::Schema::JSONSchema::SchemaCompiler::UnknownConversionError` instead

## To Reproduce

```ruby
require 'bundler/inline'

gemfile do
  gem "dry-schema"
end

require "dry-schema"

Dry::Schema.load_extensions(:json_schema)

schema = Dry::Schema.Params do
  required(:personal_info).filled(:hash) do
    required(:email).filled(:string, format?: /@/)
  end
end

schema.json_schema(loose: true)
```

## Expected behavior

A valid JSON schema 

## My environment

- Affects my production application: **YES**
- Ruby version: 2.7
- OS: ubuntu

**Comment by solnic** [comment]
What if you do:

```ruby
schema = Dry::Schema.Params do
  required(:personal_info).hash do
    required(:email).filled(:string, format?: /@/)
  end
end
```

??

**Comment by xronos-i-am** [comment]
> ```ruby
> schema = Dry::Schema.Params do
>   required(:personal_info).hash do
>     required(:email).filled(:string, format?: /@/)
>   end
> end
> ```

Nothing changed, same error

**Comment by solnic** [comment]
What if you remove the `format?` part?

**Comment by xronos-i-am** [comment]
> What if you remove the `format?` part?

It works

```ruby
{:$schema=>"http://json-schema.org/draft-06/schema#",
 :type=>"object",
 :properties=>
  {:personal_info=>
    {:type=>"object",
     :properties=>{:email=>{:type=>"string", :minLength=>1}},
     :required=>["email"]}},
 :required=>["personal_info"]}
```

**Comment by solnic** [comment]
Yeah so it's just that there's no support for `format` predicate yet.

**Comment by xronos-i-am** [comment]
not quite, the following works too:

```ruby
schema = Dry::Schema.Params do
  required(:email).filled(:string, format?: /@/)
end
```

```ruby
{:$schema=>"http://json-schema.org/draft-06/schema#",
 :type=>"object",
 :properties=>{:email=>{:type=>"string", :minLength=>1}},
 :required=>["email"]}
```

**Comment by xronos-i-am** [comment]
so, the problem is nesting

**Comment by xronos-i-am** [comment]
sorry, fixed in https://github.com/dry-rb/dry-schema/commit/35bf48e96f47158f54f19156952835f957ef6f7e
