### ISSUE TITLE
Inheriting multiple schemas

### ISSUE THREAD

**Issue by artemgurzhii** [dry-rb/dry-schema#42]
I'm having a problem with inheriting multiple schemas at once

Here is an example of what I mean

```rb
Sortable = Dry::Validation.Params do
  optional(:sort).filled
end
```

```rb
Findable = Dry::Validation.Params do
  required(:id).filled(:int?, gt?: 0)
end
```

```rb
Paginatable = Dry::Validation.Params do
  optional(:page).schema do
    required(:number).filled(:int?, gt?: 0)
    required(:size).filled(:int?, gt?: 0)
  end
end
```

```rb
IndexSchema = Dry::Validation.Params(
  ::Schemas::Concerns::Paginatable,
  ::Schemas::Concerns::Sortable,
  ::Schemas::Concerns::Findable
) do
  optional(:filter).schema do
    optional(:email).filled(:str?)
    optional(:fullname).filled(:str?)
  end
end
```

The problem comes from [here](https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation.rb#L27) as `Params` can have only one base.

**Comment by waiting-for-dev** [comment]
@solnic, about this issue, instead of talking about inheriting multiple schemas, maybe we could just recover custom and inheritable macros, which were available in dry-validation < 1. What do you think? I could try to help with it once I have a bit of time.
