### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by ShalokShalom** [dry-rb/dry-schema#422]
Is there any workflow or maintainer for the documentation (and Zulip,  for that matter?)

Since I have seen no update on the new version or any response on Zulip yet. 

https://github.com/dry-rb/dry-schema/releases/tag/v1.10.0

**Comment by solnic** [comment]
This version was yanked as it had changes that are not ready for a release. I'll release 1.10.1 during the weekend and update the docs and it'll include everything that was meant to be released in 1.10.0 excluding stuff that, well, should be excluded.
