### ISSUE TITLE
`v1.11.1` of dry-schema breaks `require "dry-validation"`

### ISSUE THREAD

**Issue by marian13** [dry-rb/dry-schema#434]
## Describe the bug

<img width="720" alt="Screenshot 2022-10-15 at 18 25 33" src="https://user-images.githubusercontent.com/22632866/195994570-0fdfa8f3-f438-44d0-91d6-8690a4e5700c.png">

## To Reproduce

Open `irb` for Ruby 2.7.

```bash
irb
```

Try to require `"dry-validation"`.

```ruby
require "dry-validation"
```

"dry-validation" version - v1.8.1.

## Expected behavior

As it was in `v1.10.0`. A successful `require`.

## My environment

- Affects my production application: **YES/NO** No.
- Ruby version: 2.7
- OS: Linux.

**Comment by marian13** [comment]
@solnic I see errors with versions upgrades happen relatively often (this is the [second one](https://github.com/dry-rb/dry-configurable/issues/146) for me in a week 😄 )

Is there a recommended approach to avoid them?

For example, right now I have something like the following in my Gemfile:

```ruby
gem "dry-validation", "~> 1.8.1"
```

Should I prefer to specify strict versions of `"dry-validation"` dependencies in it as well?

```ruby
gem "dry-validation", "1.8.1"

gem "dry-schema", "1.10.0"
```

Thanks in advance.

**Comment by solnic** [comment]
Sorry about that. We're transitioning to zeitwerk for faster gem loading and it's a complex process. Please upgrade to dry-validation 1.9.0 and dry-schema 1.11.1 (or whatever the latest version is, we may release more updates in the upcoming hours/days). If you don't want to upgrade, please just pin whatever version you used before.
