### ISSUE TITLE
Option to return `nil` values for absent keys

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-schema#44]
Dry::Struct requires any attribute to be defined in an input hash, even if it's optional and with default value. 

While it's logical behaviour, it may be not ok for different cases - for example for public API.

There are some API with optional attributes, that may change. And necessity to update all clients code every time API adds new optional field isn't desirable, even sometimes impractical.

Thus, such API should contain code logic to fulfil missed elements in hash with nil, which may be hard, especially in nested data structures. It's a boilerplate code, often ugly. 

So it'd be helpful to have an option to make `dry-validation` schema return all keys in output hash with `nil` value, even there wasn't such key in input hash. Schema already has every needed attribute defined, with correspondent type, so IMHO it's good place to put such functionality in.

It may be on more `input_processor` (however I saw input processor is in `deprecated.rb` file).

**Comment by Morozzzko** [comment]
I'm wondering if we still need this feature, as the validation result responds to `[]`, which should naturally return `nil` if the key is missing 🤔

**Comment by solnic** [comment]
I'm gonna close this because there's nothing to do here after all. We will have a schema=>struct converter soon.
