### ISSUE TITLE
High level rules inside Arrays don't return the index on the error message

### ISSUE THREAD

**Issue by mrbongiolo** [dry-rb/dry-schema#48]
Ex: 
`{:should_have_investment_rate_only=>["must be filled", "must be filled", "must be filled", "cannot be defined"], 2=>{:minimum_investment=>["is missing"]}}`

The rule `:should_have_investment_rate_only` return an array of error messages, but it's not possible to know if it was on item 1,2 or 42. It would be better if it worked like the other rules.

The schema was something like:
```
BATCH_SCHEMA = Dry::Validation.JSON do
  each do
    schema(OTHER_SCHEMA)
  end
end

OTHER_SCHEMA = Dry::Validation.JSON do
  required(:minimum_investment) #blah blah

  rule(:should_have_investment_rate_only) do
    # the rule
  end
end
```

**Comment by solnic** [comment]
I'm gonna close this one since it's actually about high-level rules which are gone here.
