### ISSUE TITLE
Make schemas quack like procs/lambdas

### ISSUE THREAD

**Issue by bbozo** [dry-rb/dry-schema#56]
At the moment you use schemas like:

```
    ClientRequest = Dry::Schema.Params do
      required(:request_id) { filled? > str? }
      required(:client_logid).filled(:string)
      required(:name).filled(:string)
      required(:currency).filled(:string)
    end

  ClientRequest.call(client_logid: 'foo', name: 'Foo', currency: 'EUR')
```

if you were to mix in something like this into `Dry::Schema.Params`:

```
module Functional
  def method_call
    method(:call)
  end

  delegate :>>, :<<, to: :method_call

  alias_method :as_proc, :method_call

  def [] *args, &block
    call(*args, &block)
  end
end
```

you would get full inter-operability with the "ruby lambda ecosystem", ie:

1. use the same short syntax for calling schemas like you do with lambdas `ClientRequest[client_logid: 'foo', name: 'Foo', currency: 'EUR']`
2. you would get compatibility with [rxruby](https://github.com/ReactiveX/RxRuby) and similar functional libraries
3. you would be able to use Ruby 2.6 function composition ie: `(UserValidator >> ApiValidator >> SomeProcOrMethodDoingValidating)[request]`
4. ...

I have been using "functional" mixins with "single public method classes" in my code for years now, I have only good things to say about it and the flexibility it allows you to play with and mix components :+1:

**Comment by solnic** [comment]
Ah I totally forgot to bring back this functionality. It'll be added for sure!

**Comment by solnic** [comment]
I added `#to_proc` and `#[]`, this should be enough. For `#>>` and `#<<` I think dry-validation will be a better place.
