### ISSUE TITLE
Upgrade to latest dry-types

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-schema#88]

**Comment by flash-gordon** [comment]
@solnic why didn't this get closed automatically? 🤔 It seems `Done` doesn't change the status of an issue

**Comment by flash-gordon** [comment]
I'm not sure if I follow what's happening 😅

**Comment by solnic** [comment]
@flash-gordon I don't know, in fact, I noticed this yesterday and was about to ask you the same question 🤷‍♂️
