### ISSUE TITLE
Return empty list for predicates without errors

### ISSUE THREAD

**Issue by waiting-for-dev** [dry-rb/dry-schema#90]
`Result#errors` and sibling methods are returning a list when there are errors on the predicate given as key or `nil` when there is none.

When there is no items for a list it makes more sense to return the empty list instead of `nil`, this way you don't have to ask for the type in your code:

```ruby
# Now
result.errors.map(&:html_for_errors) unless result.errors.nil?

# With the proposal
result.errors.map(&:html_for_errors)
```

I would happily try a PR if you like the idea.

**Comment by solnic** [comment]
I'm actually in the process of refactoring how errors are handled (see dry-rb/dry-validation#475), so coincidentally what you proposed here will be done. `Result#{errors,messages}` will return `MessageSet` object, which is a hash-compatible enumerable.

**Comment by solnic** [comment]
Starting from `0.4.0` `Result#{errors,messages,hints}` always returns a message set object, even when it's empty. It'll be released within the next couple of days.
