### ISSUE TITLE
JSON schema with `each` doesn't coerce

### ISSUE THREAD

**Issue by mauricioszabo** [dry-rb/dry-schema#96]
The following schema:

```ruby
  some_schema = Dry::Schema.JSON do
    required(:date1).filled(:time)
    required(:items).each do
      schema do
        required(:date2).filled(:time)
      end
    end
  end
```

Will parse correctly the code: `some_schema.call({date1: "2018-10-12T10:00:00Z", items: []})`, and coerce the `date1` key to time, but will not parse:

```ruby
>> some_schema.call({date1: "2018-10-12T10:00:00Z", items: [{date2: "2018-10-12T10:00:00Z"}]})
=> #<Dry::Schema::Result{:date1=>2018-10-12 10:00:00 UTC, :items=>[{:date2=>"2018-10-12T10:00:00Z"}]} errors={:items=>{0=>{:date2=>["must be a time"]}}}>
```

**Comment by flash-gordon** [comment]
Meaning of `each` and `schema` was changed in 1.0. You want to use `array` and `hash` instead, they apply types:

```ruby
  some_schema = Dry::Schema.JSON do
    required(:date1).filled(:time)
    required(:items).array do
      hash do
        required(:date2).filled(:time)
      end
    end
  end
```

Once you get used to it, it'll feel great.

**Comment by mauricioszabo** [comment]
How do I install 1.0? It's not on Rubygems, is it?

**Comment by mauricioszabo** [comment]
(also, I just saw that `.array` and `.hash` works fine with `0.3.0`. Is the documentation updated, or can I help with it?

**Comment by flash-gordon** [comment]
hah, yeah, I had dry-validation in my mind :) Use 0.3.0, it's there already https://github.com/dry-rb/dry-schema/blob/v0.3.0/lib/dry/schema/macros/hash.rb

What comes to docs I'm not sure, @solnic do you know?

**Comment by solnic** [comment]
> Is the documentation updated, or can I help with it?

nope, it's now outdated :( in general, I'd say user docs should be rewritten.

**Comment by solnic** [comment]
I actually start to think now all these methods should use types, the reason why `hash` and `array` were added was to have the ability to specify additional rules for hashes and arrays like `array(min_size?: 2).each(:int?)` but I don't see any reason why `each` and `schema` should set types for potential coercions 🤔
